name: 'NodeJS and PNPM install'
description: 'Run NodeJS, PNPM and dependencies install'

runs:
  using: 'composite'
  steps:
    - name: Install PNPM version from package.json packageManager
      uses: pnpm/action-setup@v4
      with:
        run_install: false
    - name: Get PNPM store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
    - name: Cache rotation keys
      shell: bash
      run: |
        echo "YEAR_MONTH=$(/bin/date -u "+%Y%m")" >> $GITHUB_OUTPUT
    - name: Setup PNPM cache
      uses: actions/cache@v4
      with:
        path: |
          ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ env.YEAR_MONTH }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-${{ env.YEAR_MONTH }}-
    - name: Setup Wireit cache
      uses: google/wireit@setup-github-actions-caching/v2
    - name: Install dependencies
      shell: bash
      run: pnpm --frozen-lockfile --prefer-offline install
      env:
        # Other environment variables
        HUSKY: '0' # By default do not run HUSKY install
