name: 'Create env file'
description: 'Create a local .env.local file given required environment variables'

inputs:
  firebase_api_key:
    type: string
    required: true
  firebase_app_id:
    type: string
    required: true
  firebase_auth_domain:
    type: string
    required: true
  firebase_measurement_id:
    type: string
    required: true
  firebase_messaging_sender_id:
    type: string
    required: true
  firebase_project_id:
    type: string
    required: true
  firebase_service_account_client_email:
    type: string
    required: true
  firebase_service_account_private_key:
    type: string
    required: true
  firebase_storage_bucket:
    type: string
    required: true

runs:
  using: 'composite'
  steps:
    - name: Create envfile
      uses: SpicyPizza/create-envfile@v2.0
      with:
        envkey_NUXT_FIREBASE_API_KEY: ${{ inputs.firebase_api_key }}
        envkey_NUXT_FIREBASE_APP_ID: ${{ inputs.firebase_app_id }}
        envkey_NUXT_FIREBASE_AUTH_DOMAIN: ${{ inputs.firebase_auth_domain }}
        envkey_NUXT_FIREBASE_MEASUREMENT_ID: ${{ inputs.firebase_measurement_id }}
        envkey_NUXT_FIREBASE_MESSAGING_SENDER_ID: ${{ inputs.firebase_messaging_sender_id }}
        envkey_NUXT_FIREBASE_PROJECT_ID: ${{ inputs.firebase_project_id }}
        envkey_NUXT_FIREBASE_SERVICE_ACCOUNT_CLIENT_EMAIL: ${{ inputs.firebase_service_account_client_email }}
        envkey_NUXT_FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY: ${{ inputs.firebase_service_account_private_key }}
        envkey_NUXT_FIREBASE_STORAGE_BUCKET: ${{ inputs.firebase_storage_bucket }}
        file_name: .env.local
        fail_on_empty: true
