name: 'QA staging'

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  check:
    name: Staging check
    uses: ./.github/workflows/check.yml
    secrets:
      git_crypt_key: ${{ secrets.GIT_CRYPT_KEY }}
  build:
    name: Staging build
    uses: ./.github/workflows/build.yml
    with:
      firebase_env: staging
    secrets:
      git_crypt_key: ${{ secrets.GIT_CRYPT_KEY }}
  test-e2e:
    name: Staging e2e tests
    needs:
      - build
    uses: ./.github/workflows/test-e2e.yml
    with:
      firebase_env: staging
    secrets:
      git_crypt_key: ${{ secrets.GIT_CRYPT_KEY }}
  test-unit:
    name: Staging unit tests
    uses: ./.github/workflows/test-unit.yml
    secrets:
      git_crypt_key: ${{ secrets.GIT_CRYPT_KEY }}
