on:
  workflow_call:
    inputs:
      firebase_env:
        type: string
        required: true
      base_url:
        type: string
        required: false

jobs:
  test-e2e:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout git project
        uses: actions/checkout@v4
      - name: Install PNPM and dependencies
        uses: ./.github/actions/pnpm-install
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: 'build'
      - name: Install playwright
        run: pnpm run playwright:install
      - name: Run e2e tests
        run: pnpm run test:e2e
        env:
          PLAYWRIGHT_BASE_URL: ${{ inputs.base_url }}
